export const REQUEST_API = 'REQUEST_API';

export const RESET_ERROR = 'RESET_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const RESTORE_SESSION = 'RESTORE_SESSION';
export const UNAUTH_USER = 'UNAUTH_USER';

export const GET_PERSONS_REQUEST = 'GET_PERSONS_REQUEST';
export const GET_PERSONS_SUCCESS = 'GET_PERSONS_SUCCESS';
export const GET_PERSONS_FAILURE = 'GET_PERSONS_FAILURE';
export const UPDATE_PERSONS = 'UPDATE_PERSONS';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const PERSON_RESET = 'PERSON_RESET';

export const PERSON_CREATE_REQUEST = 'PERSON_CREATE_REQUEST';
export const PERSON_CREATE_SUCCESS = 'PERSON_CREATE_SUCCESS';
export const PERSON_CREATE_FAILURE = 'PERSON_CREATE_FAILURE';
export const PERSON_GET_REQUEST = 'PERSON_GET_REQUEST';
export const PERSON_GET_SUCCESS = 'PERSON_GET_SUCCESS';
export const PERSON_GET_FAILURE = 'PERSON_GET_FAILURE';
export const PERSON_UPDATE_REQUEST = 'PERSON_UPDATE_REQUEST';
export const PERSON_UPDATE_SUCCESS = 'PERSON_UPDATE_SUCCESS';
export const PERSON_UPDATE_FAILURE = 'PERSON_UPDATE_FAILURE';
export const PERSON_DELETE_REQUEST = 'PERSON_DELETE_REQUEST';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';
export const PERSON_DELETE_AVATAR = 'PERSON_DELETE_AVATAR';

export const FORM_FIELD_UPDATE = 'FORM_FIELD_UPDATE';

export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';

export const TOGGLE_PRELOADER = 'TOGGLE_PRELOADER';
